### ISSUE TITLE
Exception in console

### ISSUE THREAD

**Issue by bizoo** [alek-sys/ChangeTracker#1]
Didn't have time to debug now but this is the message:

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 282, in run_
  File ".\changetracker.py", line 90, in run
  File ".\changetracker.py", line 71, in highlight
  File ".\changetracker.py", line 63, in is_enabled
  File ".\genericpath.py", line 49, in getsize
TypeError: coercing to Unicode: need string or buffer, NoneType found

startup, version: 2144 windows x64 channel: dev

**Comment by bizoo** [comment]
It's probably caused by the console itself.
Trying to get the view.file_name() of the console ?
